#!/bin/sh
rm /opt/hadoop-2.4.0/etc/hadoop
ln -s /opt/hadoop-2.4.0/etc/hadoop.pseudo /opt/hadoop-2.4.0/etc/hadoop
start-dfs.sh
start-yarn.sh
hdfs dfsadmin -safemode leave
mr-jobhistory-daemon.sh start historyserver
